const bonus = {
  coin: "coin",
  supply: "supply",
  good: "good",
  special_good: "special_good",
  good_bonus: "good_bonus",
  expansion: "expansion",
  medal: "medal",
  diamond: "diamond",
  pvp_tower: "pvp_tower",
  military_boost: "Military boost",
  fierce_resistance: "fierce_resistance",
  coin_boost: "coin_boost",
  supply_boost: "supply_boost",
  good_production: "good_production",
  medal_production: "medal_production",
  research: "research",
  coin_production: "coin_production",
  supply_production: "supply_production",
  population: "population",
  happiness: "happiness",
  quest_reward_boost: "quest_reward_boost",
  penal_unit: "penal_unit",
  guild_goods: "guild_goods",
  support_pool_bonus: "support_pool_bonus",
  aid_goods: "aid_goods",
  plunder_goods: "plunder_goods",
  contribution_boost: "contribution_boost",
  aid_blueprints: "aid_blueprints",
  relic_hunt: "relic_hunt",
  critical_hit: "critical_hit",
  helping_hands: "helping_hands",
  plunder_and_pillage: "plunder_and_pillage",
  first_strike: "first_strike",
  double_collection: "double_collection"
};

module.exports.bonus = bonus;
